# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAiwXN5jb5oeYhFChgVkuxH7lcVPgdzi
"""

#!pip install streamlit

# Importamos las librerías
import streamlit as st
import pandas as pd
import yfinance as yf

st.title ("Mi primera aplicacion en Streamlit 🚀")

# Lista de ticker incial
lista_tickers = ["AAPL","MSFT","NVDA","META"]

#Multiselector

ticker=st.multoselect("Elija un ticker o varios",lista_tickers)

# Botón

if st.button("Descargar"):
  data=yf.download(ticker,period="1mo")[Close]
  st.subheader("📋 Precios de cierre")
  st.dataframe(data)
