# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAiwXN5jb5oeYhFChgVkuxH7lcVPgdzi
"""

!pip install streamlit

# Importamos las librerías
import streamlit as st
import pandas as pd

st.title ("Mi primera aplicacion en Streamlit 🚀")